name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  ci:
    name: CI
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.18"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install dependencies
        run: uv sync
      
      - name: Run format
        run: make fmt

      - name: Run lint
        run: make lint

      - name: Run test
        run: make test
